# Generated by Django 3.2.16 on 2022-11-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.SmallIntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('date_order', models.CharField(max_length=100)),
                ('time_zone', models.IntegerField()),
                ('status', models.SmallIntegerField(default=0, verbose_name='status')),
                ('orders', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('directioncustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.directioncustomer')),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.dispatcher')),
            ],
        ),
    ]
